#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-jquery-rails
Version  : 4.1.0
Release  : 5
URL      : https://rubygems.org/downloads/jquery-rails-4.1.0.gem
Source0  : https://rubygems.org/downloads/jquery-rails-4.1.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-railties
BuildRequires : rubygem-rdoc

%description
# jquery-rails
jQuery! For Rails! So great.
This gem provides:
* jQuery 1 and jQuery 2
* the jQuery UJS adapter
* assert_select_jquery to test jQuery responses in Ruby tests

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n jquery-rails-4.1.0
gem spec %{SOURCE0} -l --ruby > rubygem-jquery-rails.gemspec

%build
gem build rubygem-jquery-rails.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
jquery-rails-4.1.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/jquery-rails-4.1.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/VERSIONS.md
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/jquery-rails.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/lib/jquery-rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/lib/jquery/assert_select.rb
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/lib/jquery/rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/lib/jquery/rails/engine.rb
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/lib/jquery/rails/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/test/assert_select_jquery_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/vendor/assets/javascripts/jquery.js
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/vendor/assets/javascripts/jquery.min.js
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/vendor/assets/javascripts/jquery.min.map
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/vendor/assets/javascripts/jquery2.js
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/vendor/assets/javascripts/jquery2.min.js
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/vendor/assets/javascripts/jquery2.min.map
/usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-4.1.0/vendor/assets/javascripts/jquery_ujs.js
/usr/lib64/ruby/gems/2.3.0/specifications/jquery-rails-4.1.0.gemspec
