#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-jquery-rails
Version  : 4.0.4
Release  : 2
URL      : https://rubygems.org/downloads/jquery-rails-4.0.4.gem
Source0  : https://rubygems.org/downloads/jquery-rails-4.0.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-railties
BuildRequires : rubygem-rdoc

%description
# jquery-rails
jQuery! For Rails! So great.
This gem provides:
* jQuery 1.11.1 and jQuery 2.1.1
* the jQuery UJS adapter
* assert_select_jquery to test jQuery responses in Ruby tests

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n jquery-rails-4.0.4
gem spec %{SOURCE0} -l --ruby > rubygem-jquery-rails.gemspec

%build
gem build rubygem-jquery-rails.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
jquery-rails-4.0.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/jquery-rails-4.0.4.gem
/usr/lib64/ruby/gems/2.2.0/doc/jquery-rails-4.0.4/ri/Jquery/Rails/Engine/cdesc-Engine.ri
/usr/lib64/ruby/gems/2.2.0/doc/jquery-rails-4.0.4/ri/Jquery/Rails/cdesc-Rails.ri
/usr/lib64/ruby/gems/2.2.0/doc/jquery-rails-4.0.4/ri/Jquery/cdesc-Jquery.ri
/usr/lib64/ruby/gems/2.2.0/doc/jquery-rails-4.0.4/ri/Rails/Dom/Testing/Assertions/SelectorAssertions/assert_select_jquery-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/jquery-rails-4.0.4/ri/Rails/Dom/Testing/Assertions/SelectorAssertions/cdesc-SelectorAssertions.ri
/usr/lib64/ruby/gems/2.2.0/doc/jquery-rails-4.0.4/ri/Rails/Dom/Testing/Assertions/SelectorAssertions/unescape_js-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/jquery-rails-4.0.4/ri/Rails/Dom/Testing/Assertions/cdesc-Assertions.ri
/usr/lib64/ruby/gems/2.2.0/doc/jquery-rails-4.0.4/ri/Rails/Dom/Testing/cdesc-Testing.ri
/usr/lib64/ruby/gems/2.2.0/doc/jquery-rails-4.0.4/ri/Rails/Dom/cdesc-Dom.ri
/usr/lib64/ruby/gems/2.2.0/doc/jquery-rails-4.0.4/ri/Rails/cdesc-Rails.ri
/usr/lib64/ruby/gems/2.2.0/doc/jquery-rails-4.0.4/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/README.md
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/VERSIONS.md
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/jquery-rails.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/lib/jquery-rails.rb
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/lib/jquery/assert_select.rb
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/lib/jquery/rails.rb
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/lib/jquery/rails/engine.rb
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/lib/jquery/rails/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/vendor/assets/javascripts/jquery.js
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/vendor/assets/javascripts/jquery.min.js
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/vendor/assets/javascripts/jquery.min.map
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/vendor/assets/javascripts/jquery2.js
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/vendor/assets/javascripts/jquery2.min.js
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/vendor/assets/javascripts/jquery2.min.map
/usr/lib64/ruby/gems/2.2.0/gems/jquery-rails-4.0.4/vendor/assets/javascripts/jquery_ujs.js
/usr/lib64/ruby/gems/2.2.0/specifications/jquery-rails-4.0.4.gemspec
